name: SovereignMCMovecraftAddons
version: '1.0-SNAPSHOT'
main: net.sovereignmc.sovereignmcmovecraftaddons.SovereignMCMovecraftAddons
api-version: '1.20'

commands:
  # rotate alias
  ror:
    description: Rotate craft right
    usage: /ror
  rol:
    description: Rotate craft left
    usage: /rol
  testing:
    description: testing for whatever
    usage: /test
  cleardisplays:
    description: Removes all TextDisplay entities within 3 blocks.
    usage: /cleardisplays
  allowedblocks:
    description: Allowed Blocks
    usage: /allowedblocks
  craftcomp:
    description: Craft CraftCalculation
    usage: /craftcomp
  ammo:
    description: Ammunition
    usage: /ammo
  craftstorage:
    description: Craft Storage
    usage: /craftstorage